name: Publish Assistant-IA Package

on:
  push:
    tags:
      - "package-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm install
        working-directory: package

      - name: Publish package
        run: npm publish
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
